# Generated by Django 4.2.7 on 2023-12-07 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_blog_posted_alter_comment_date_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 14, 32, 9, 701248), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 7, 14, 32, 9, 703243), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(default='temp2.jpg', upload_to='', verbose_name='Путь к изображению'),
        ),
    ]
